// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAMhovliYZPeCnfavfvqMTt3-wzsYIL9qo",
      authDomain: "mirrorestate-90e67.firebaseapp.com",
      projectId: "mirrorestate-90e67",
      storageBucket: "mirrorestate-90e67.firebasestorage.app",
      messagingSenderId: "685724866691",
      appId: "1:685724866691:web:ef6127a490b0f9da2863b6",
      measurementId: "G-Q7V2LN5D42"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQaGVMxnIzmrgtcozvt6kWKaTsVi2Zh4',
    appId: '1:685724866691:android:4adb16bead7926cb2863b6',
    messagingSenderId: '685724866691',
    projectId: 'mirrorestate-90e67',
    storageBucket: 'mirrorestate-90e67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9yn2i1JNvodemETp5-Visjb8XiDsAyIo',
    appId: '1:685724866691:ios:2e149ace1412f25d2863b6',
    messagingSenderId: '685724866691',
    projectId: 'mirrorestate-90e67',
    storageBucket: 'mirrorestate-90e67.firebasestorage.app',
    iosBundleId: 'com.example.ass',
  );
}
