// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBERNdv4ruGApWG-QH0VWuBQ_Kg2iw1agA",
      authDomain: "planner-18ecd.firebaseapp.com",
      projectId: "planner-18ecd",
      storageBucket: "planner-18ecd.appspot.com",
      messagingSenderId: "1068854125213",
      appId: "1:1068854125213:web:3c8371c4d7d0672abdea74",
      measurementId: "G-22DR6M87X1"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkOpv_tvpjX1QtvDxycjgY-VacoOkGuI0',
    appId: '1:1068854125213:android:776d21043661c862bdea74',
    messagingSenderId: '1068854125213',
    projectId: 'planner-18ecd',
    storageBucket: 'planner-18ecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN1dBVOIz-jWAN0m5Y4MUjncyYrW-xow8',
    appId: '1:1068854125213:ios:46d0bb5d3cc1dd2fbdea74',
    messagingSenderId: '1068854125213',
    projectId: 'planner-18ecd',
    storageBucket: 'planner-18ecd.appspot.com',
    iosBundleId: 'com.example.ass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN1dBVOIz-jWAN0m5Y4MUjncyYrW-xow8',
    appId: '1:1068854125213:ios:46d0bb5d3cc1dd2fbdea74',
    messagingSenderId: '1068854125213',
    projectId: 'planner-18ecd',
    storageBucket: 'planner-18ecd.appspot.com',
    iosBundleId: 'com.example.ass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERNdv4ruGApWG-QH0VWuBQ_Kg2iw1agA',
    appId: '1:1068854125213:web:dde701b607394746bdea74',
    messagingSenderId: '1068854125213',
    projectId: 'planner-18ecd',
    authDomain: 'planner-18ecd.firebaseapp.com',
    storageBucket: 'planner-18ecd.appspot.com',
    measurementId: 'G-S6SBHHHDM7',
  );
}
